[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[colors.bright]
black = "#928374"
blue = "#83A598"
cyan = "#8EC07C"
green = "#B8BB26"
magenta = "#D3869B"
red = "#FB4934"
white = "#EBDBB2"
yellow = "#FABD2F"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689D6A"
green = "#98971A"
magenta = "#B16286"
red = "#CC241D"
white = "#A89984"
yellow = "#D79921"

[colors.primary]
background = "#000000"

[font]
size = 12

[font.normal]
#family = "Unifont"
family = "PxPlus IBM VGA 9x16"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 0.65
resize_increments = true

[window.dimensions]
columns = 98
lines = 28

[window.padding]
x = 18
y = 18
