[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#FFFFFF"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#83a598"
cyan = "#b8bb26"
green = "#83a598"
magenta = "#fb4934"
red = "#fabd2f"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#2f2f2f"

[font]
size = 12

[font.normal]
#family = "Ubuntu Mono"
family = "PxPlus IBM VGA 9x16"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 0.3
resize_increments = true

[window.dimensions]
columns = 50
lines = 40

[window.padding]
x = 18
y = 18
